app:
  title: "RAG System"
  description: "Retrieval-Augmented Generation for Document QA"
  model: "llama3-8b-8192
  host: "0.0.0.0"
  port: 8501

vector_store:
  persist_directory: "./data/processed"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  top_k: 5

ingestion:
  chunk_size: 500
  chunk_overlap: 50

logging:
  level: INFO
  json: true
  dir: "./logs"

llm:
  provider: groq
  temperature: 0.2
  max_tokens: 512
